# Generated by Django 5.1.5 on 2026-08-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0004_alter_clipboarditems_uniquecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboarditems',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
