# Generated by Django 5.1.5 on 2026-09-30 20:58

from django.db import migrations

def forward_unlogged(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE clipboard_clipboarditems SET UNLOGGED;")

def reverse_unlogged(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE clipboard_clipboarditems SET LOGGED;")


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0005_clipboarditems_expires_at'),
    ]

    operations = [
        migrations.RunPython(forward_unlogged, reverse_unlogged),
    ]
