# Generated by Django 5.1.5 on 2026-09-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0006_auto_20261001_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clipboarditems',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='clipboarditems',
            name='image',
        ),
        migrations.AddField(
            model_name='clipboarditems',
            name='document_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clipboarditems',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
