# Generated by Django 5.1.2 on 2024-10-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboardiems',
            name='UniqueCode',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
