# Generated by Django 5.1.2 on 2024-10-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0003_rename_clipboardiems_clipboarditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboarditems',
            name='UniqueCode',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
